services:
  netalertx:
    network_mode: host                   # Use host networking for ARP scanning and other services
    build:
      context: .                         # Build context is the current directory   
      dockerfile: Dockerfile             # Specify the Dockerfile to use    
    image: netalertx:latest
    container_name: netalertx            # The name when you docker contiainer ls
    read_only: true                      # Make the container filesystem read-only
    # cap_drop:                           # Drop all capabilities for enhanced security
    #   - ALL
    cap_add:                            # Add only the necessary capabilities
      - NET_ADMIN                       # Required for ARP scanning
      - NET_RAW                         # Required for raw socket operations
    security_opt:                       # Security options for the container
      - no-new-privileges:true          # Prevent privilege escalation
      - seccomp:unconfined               # Use unconfined seccomp profile (adjust as needed)
    volumes:
      - netalertx_config:/app/config
      - netalertx_db:/app/db
      - /etc/localtime:/etc/localtime:ro

    tmpfs:
      - "/app/api:uid=20211,gid=20211,mode=700"
      - "/app/log:uid=20211,gid=20211,mode=700"
      - "/services/config/nginx/conf.active:uid=20211,gid=20211,mode=700"
      - "/services/run:uid=20211,gid=20211,mode=700"
      - "/tmp:mode=700"


    environment:
      NETALERTX_MODE: hardened
      PORT: 20211
      GRAPHQL_PORT: 25378
      ALWAYS_FRESH_INSTALL: false
    restart: unless-stopped

volumes:
  netalertx_config:
  netalertx_db:
 
