version: '3.8'

services:
  netalertx:
    build:
      context: .
      dockerfile: Dockerfile
    image: netalertx:latest
    container_name: netalertx_unproxied
    read_only: true
    tmpfs:
      - /etc/nginx/conf.d
      - /var/cache/nginx
      - /var/run
      - /app/log
      - /tmp
    network_mode: "host"
    environment:
      - NETALERTX_MODE=unproxied
      - GRAPHQL_PORT=20212
    restart: unless-stopped
