name: Enhancement Request
description: Propose an improvement to an existing feature or UX behavior.
labels: ['enhancement ♻️']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    options:
      - label: I have searched existing open and closed issues
        required: true
- type: textarea
  attributes:
    label: What is the enhancement?
    description: Describe the change or optimization you’d like to see to an existing feature.
    placeholder: e.g. Make scan intervals configurable from UI instead of just `app.conf`
    required: true
- type: textarea
  attributes:
    label: What problem does this solve or improve?
    description: Describe why this change would improve user experience or project maintainability.
    required: true
- type: textarea
  attributes:
    label: Additional context or examples
    description: |
      Screenshots? Comparisons? Reference repos?
    required: false
- type: checkboxes
  attributes:
    label: Are you willing to help implement this?
    options:
      - label: "Yes"
      - label: "No"
