name: Refactor / Code Quality Request ♻️
description: Suggest improvements to code structure, style, or maintainability.
labels: ['enhancement ♻️']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please check if a similar request already exists.
    options:
      - label: I have searched the existing open and closed issues
        required: true
- type: textarea
  attributes:
    label: What part of the code needs refactoring or improvement?
    description: Specify files, modules, or components.
    required: true
- type: textarea
  attributes:
    label: Describe the proposed changes
    description: Explain the refactoring or quality improvements you suggest.
    required: true
- type: textarea
  attributes:
    label: Why is this improvement needed?
    description: Benefits such as maintainability, readability, performance, or scalability.
    required: true
- type: textarea
  attributes:
    label: Additional context or examples
    description: Any relevant links, references, or related issues.
    required: false
- type: checkboxes
  attributes:
    label: Can you help implement this change?
    options:
      - label: Yes
      - label: No
