name: Setup help
description: 'When submitting an issue enable LOG_LEVEL="trace" and re-search first.'
labels: ['Setup 📥']
body:
- type: checkboxes
  attributes:
    label: Did I research?
    description: Please confirm you checked the usual places before opening a setup support request.
    options:
    - label: I have searched the docs https://jokob-sk.github.io/NetAlertX/
      required: true
    - label: I have searched the existing open and closed issues
      required: true
    - label: I confirm my SCAN_SUBNETS is configured and tested as per https://github.com/jokob-sk/NetAlertX/blob/main/docs/SUBNETS.md
      required: true
- type: checkboxes
  attributes:
    label: The issue occurs in the following browsers. Select at least 2.
    description: This step helps me understand if this is a cache or browser-specific issue. 
    options:
    - label: "Firefox"
    - label: "Chrome"
    - label: "Other (unsupported) - PRs welcome"
    - label: "N/A - This is an issue with the backend"
- type: textarea
  attributes:
    label: What I want to do
    description: Describe what you want to achieve.
  validations:
    required: false
- type: textarea
  attributes:
    label: Relevant settings you changed
    description: |
      Paste a screenshot or setting values of the settings you changed. 
  validations:
    required: false
- type: textarea
  attributes:
    label: docker-compose.yml
    description: |
      Paste your `docker-compose.yml`    
    render: python
  validations:
    required: false
- type: dropdown
  id: installation_type
  attributes:
    label: What installation are you running?
    options:
      - Production (netalertx)
      - Dev (netalertx-dev)
      - Home Assistant (addon)
      - Home Assistant fa (full-access addon)
      - Bare-metal (community only support - Check Discord)
  validations:
    required: true
- type: textarea
  attributes:
    label: app.log
    description: |
      Logs with debug enabled (https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEBUG_TIPS.md) ⚠
      ***Generally speaking, all bug reports should have logs provided.***
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      Additionally, any additional info? Screenshots? References? Anything that will give us more context about the issue you are encountering!
      You can use `tail -100 /app/log/app.log` in the container if you have trouble getting to the log files. 
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Debug enabled
    description: I confirm I enabled `debug`
    options:
    - label: I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.
      required: true
