name: Translation / Localization Request 🌐
description: Suggest adding or improving translations or localization support.
labels: ['enhancement 🌐']
body:
- type: checkboxes
  attributes:
    label: Have you checked for existing translation efforts or related issues?
    options:
      - label: I have searched existing open and closed issues
        required: true
- type: textarea
  attributes:
    label: Language(s) involved
    description: Specify the language(s) this request pertains to.
    required: true
- type: textarea
  attributes:
    label: Describe the translation or localization improvement
    description: Examples include adding new language support, fixing translation errors, or improving formatting.
    required: true
- type: textarea
  attributes:
    label: Why is this important for the project or users?
    description: Describe the benefits or target audience.
    required: false
- type: textarea
  attributes:
    label: Additional context or references
    description: Link to files, previous translation PRs, or external resources.
    required: false
- type: checkboxes
  attributes:
    label: Can you help with translation or review?
    options:
      - label: Yes
      - label: No
