name: 📧 Social Posts
on:
  release:
    types: [published]

jobs:
  post-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 15 minutes
        run: sleep 900  # 15 minutes delay

      - name: Post to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "🎉 New release: **${{ github.event.release.name }}** is live! 🚀\nCheck it out here: ${{ github.event.release.html_url }}"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

